/*
 * generated by Xtext
 */
package org.dpolivaev.testgeneration.dsl.validation

import org.eclipse.xtext.validation.Check
import org.eclipse.xtext.xbase.XExpression
import org.dpolivaev.testgeneration.dsl.testspec.LabeledExpression
import org.dpolivaev.testgeneration.dsl.testspec.RuleGroup
import org.dpolivaev.testgeneration.dsl.testspec.TestspecPackage

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class TestSpecValidator extends AbstractTestSpecValidator {
	@Check
	override checkInnerExpressions(XExpression expr) {
		val container = expr.eContainer
		switch(container){
			 LabeledExpression case container.reason == expr: return
		} 
		super.checkInnerExpressions(expr)
	}
	
	@Check
	def checkNamedRule(RuleGroup ruleGroup){
		if (ruleGroup.ruleName != null || ! ruleGroup.ruleNameExpressions.empty) {
			val feature = if (ruleGroup.ruleName != null) TestspecPackage.Literals.RULE_GROUP__RULE_NAME else TestspecPackage.Literals.RULE_GROUP__RULE_NAME_EXPRESSIONS
			if(ruleGroup.rule == null){
				error("name without rule", ruleGroup,  feature)			
				return;
			}
			if(ruleGroup.rule.^default){
				error("named default rule", ruleGroup, feature)			
				return;
			}
			if(ruleGroup.rule.specialValue != null){
				error("named special rule", ruleGroup, feature)			
				return;
			}
		}
	}
}
