/*
 * generated by Xtext
 */
package org.dpolivaev.testgeneration.dsl;

import org.dpolivaev.testgeneration.dsl.jvmmodel.StrategyCompiler;
import org.dpolivaev.testgeneration.dsl.jvmmodel.StrategyEarlyExitComputer;
import org.dpolivaev.testgeneration.dsl.scoping.StrategyDslImplicitlyImportedTypes;
import org.dpolivaev.testgeneration.dsl.typesystem.StrategyTypeComputer;
import org.dpolivaev.testgeneration.dsl.naming.ValuesXBaseNameProvider;
import org.eclipse.xtext.xbase.compiler.XbaseCompiler;
import org.eclipse.xtext.xbase.controlflow.IEarlyExitComputer;
import org.eclipse.xtext.xbase.scoping.batch.ImplicitlyImportedTypes;
import org.eclipse.xtext.xbase.typesystem.computation.ITypeComputer;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StrategyDslRuntimeModule extends org.dpolivaev.testgeneration.dsl.AbstractStrategyDslRuntimeModule {
	public Class<? extends XbaseCompiler> bindXbaseCompiler() {
		return StrategyCompiler.class;
	}
	
	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return ValuesXBaseNameProvider.class;
	}

	@Override
	public Class<? extends ITypeComputer> bindITypeComputer() {
		return StrategyTypeComputer.class;
	}
	
	@Override
	public Class<? extends org.eclipse.xtext.formatting.IFormatter> bindIFormatter() {
		return org.dpolivaev.testgeneration.dsl.formatting.StrategyDslFormatter.class;
	}
	
	public Class<? extends IEarlyExitComputer> bindIEarlyExitComputer() {
		return StrategyEarlyExitComputer.class;
	}

	public Class<? extends ImplicitlyImportedTypes> bindImplicitlyImportedTypes() {
		return StrategyDslImplicitlyImportedTypes.class;
	}

}
