/*
* generated by Xtext
*/
package org.dpolivaev.testgeneration.dsl;

import org.dpolivaev.testgeneration.dsl.TestSpecStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TestSpecStandaloneSetup extends TestSpecStandaloneSetupGenerated{

	public static void doSetup() {
		new TestSpecStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

