/*
 * generated by Xtext
 */
package org.dpolivaev.dsl.tsgen.validation


//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class StrategyDslValidator extends AbstractStrategyDslValidator {
}
