/*
 * generated by Xtext
 */
package org.dpolivaev.testgeneration.dsl.ui.contentassist

import org.dpolivaev.testgeneration.dsl.ui.contentassist.AbstractStrategyDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class StrategyDslProposalProvider extends AbstractStrategyDslProposalProvider {
}
