/*
 * generated by Xtext
 */
package org.dpolivaev.testgeneration.dsl.ui.contentassist

import org.dpolivaev.testgeneration.dsl.ui.contentassist.AbstractTestSpecProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TestSpecProposalProvider extends AbstractTestSpecProposalProvider {
}
