/*
 * generated by Xtext
 */
package org.dpolivaev.dsl.tsgen;

import org.dpolivaev.dsl.tsgen.jvmmodel.StrategyCompiler;
import org.dpolivaev.dsl.tsgen.typesystem.StrategyTypeComputer;
import org.dpolivaev.dsl.tsgen.validation.AbstractStrategyDslValidator;
import org.dpolivaev.dsl.tsgen.validation.StrategyDslValidator;
import org.eclipse.xtext.service.SingletonBinding;
import org.eclipse.xtext.xbase.compiler.XbaseCompiler;
import org.eclipse.xtext.xbase.typesystem.computation.ITypeComputer;
import org.xtext.scripting.validation.AbstractScriptingValidator;
import org.xtext.scripting.validation.ScriptingValidator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StrategyDslRuntimeModule extends org.dpolivaev.dsl.tsgen.AbstractStrategyDslRuntimeModule {
	public Class<? extends XbaseCompiler> bindXbaseCompiler() {
		return StrategyCompiler.class;
	}

	@Override
	public Class<? extends ITypeComputer> bindITypeComputer() {
		return StrategyTypeComputer.class;
	}
	
	@Override
	public Class<? extends org.eclipse.xtext.formatting.IFormatter> bindIFormatter() {
		return org.dpolivaev.dsl.tsgen.formatting.StrategyDslFormatter.class;
	}

	@Override
	@SingletonBinding(eager=true)	
	public Class<? extends AbstractStrategyDslValidator> bindAbstractStrategyDslValidator() {
		return StrategyDslValidator.class;
	}
}
