/*
* generated by Xtext
*/
package org.dpolivaev.dsl.tsgen;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class StrategyDslStandaloneSetup extends StrategyDslStandaloneSetupGenerated{

	public static void doSetup() {
		new StrategyDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

