/*
 * generated by Xtext
 */
package org.dpolivaev.dsl.tsgen.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StrategyDslUiModule extends org.dpolivaev.dsl.tsgen.ui.AbstractStrategyDslUiModule {
	public StrategyDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
