/*
 * generated by Xtext
 */
package org.dpolivaev.dsl.tsgen.ui;

import org.dpolivaev.dsl.tsgen.ui.autoedit.StrategyDslAutoEditStrategyProvider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.autoedit.AbstractEditStrategyProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StrategyDslUiModule extends org.dpolivaev.dsl.tsgen.ui.AbstractStrategyDslUiModule {
	public StrategyDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends AbstractEditStrategyProvider>
    bindAbstractEditStrategyProvider() {
		return StrategyDslAutoEditStrategyProvider.class;
	}

}
